/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.DataTraining;
import application.dao.PemohonVisaDao;
import application.daoimpl.DataTrainingDaoImpl;
import application.daoimpl.PemohonVisaDaoImpl;
import application.models.DataTrainingModel;
import application.models.PemohonVisaModel;
import application.models.PredictionResultModel;
import application.utils.DataItem;
import application.utils.DatabaseUtil;
import application.utils.NaiveBayesAlgoritma;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.io.InputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mhdja
 */
public class PrediksiView extends javax.swing.JPanel {
    public final DataTraining dataTrainingDao;
    public final PemohonVisaDao pemohonDao;
    public Map<String, Integer> pemohonMap = new HashMap<>();
    public String hasil;
    
    public void featureDropdown() {
        // Definisikan data fitur dan pilihannya
        Map<JComboBox<String>, List<String>> featureMap = new LinkedHashMap<>();

        // Paspor
        featureMap.put(jComboBoxPaspor, Arrays.asList(
            "Jelas",
            "Terhalang jari"
        ));

        // Surat Pernyataan Jaminan
        featureMap.put(jComboBoxSPJ, Arrays.asList(
            "Ada",
            "Tidak ada"
        ));

        // Rekening Koran Sponsor
        featureMap.put(jComboBoxRKS, Arrays.asList(
            "3 bulan terakhir",
            "Kurang dari 3 bulan terakhir"
        ));

        // CV
        featureMap.put(jComboBoxCV, Arrays.asList(
            "Relevan",
            "Tidak relevan"
        ));

        // Jadwal Keberangkatan
        featureMap.put(jComboBoxJadwalKeberangkatan, Arrays.asList(
            "Jelas",
            "Tidak jelas"
        ));

        // Iterasi dan isi setiap combo box
        for (Map.Entry<JComboBox<String>, List<String>> entry : featureMap.entrySet()) {
            JComboBox<String> comboBox = entry.getKey();
            List<String> values = entry.getValue();

            comboBox.removeAllItems();
            for (String value : values) {
                comboBox.addItem(value);
            }
        }

        // Tambahkan data pemohon ke combo box
        jComboBoxPemohon.removeAllItems();
        List<PemohonVisaModel> listPemohon = pemohonDao.findAll();
        for (PemohonVisaModel pemohon : listPemohon) {
            jComboBoxPemohon.addItem(pemohon.getNamaPemohon()); // Menampilkan nama pemohon
            pemohonMap.put(pemohon.getNamaPemohon(), pemohon.getId()); // Simpan ID berdasarkan nama
        }
        
    }



    /**
     * Creates new form PrediksiView
     */
    public PrediksiView() {
        initComponents();
        this.dataTrainingDao = new DataTrainingDaoImpl();
        this.pemohonDao = new PemohonVisaDaoImpl();
        
        featureDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxCV = new javax.swing.JComboBox<>();
        jComboBoxPaspor = new javax.swing.JComboBox<>();
        jComboBoxSPJ = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPemohon = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxRKS = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxJadwalKeberangkatan = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Paspor");

        jLabel2.setText("Surat Pernyataan Jaminan\t");

        jLabel3.setText("Rekening Koran Sponsor");

        jButton1.setText("HASIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPaspor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPaspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPasporActionPerformed(evt);
            }
        });

        jComboBoxSPJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSPJActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("PREDIKSI");

        jLabel5.setText("Pemohon Visa");

        jComboBoxPemohon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPemohon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPemohonActionPerformed(evt);
            }
        });

        jLabel6.setText("CV Pengalaman Kerja/Pendidikan");

        jComboBoxRKS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRKSActionPerformed(evt);
            }
        });

        jLabel7.setText("Jadwal Keberangkatan");

        jComboBoxJadwalKeberangkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJadwalKeberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJadwalKeberangkatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxPaspor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPemohon, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxRKS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxCV, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxJadwalKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPemohon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPaspor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxJadwalKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jButton2.setText("CETAK LAPORAN PREDIKSI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         System.out.println("=== Mulai Proses Prediksi ===");

        List<DataItem> trainingData = this.dataTrainingDao.findAsDataItem();
        System.out.println("Jumlah data training diambil: " + trainingData.size());

        // Ambil pemohon yang dipilih
        String selectedName = (String) jComboBoxPemohon.getSelectedItem();
        Integer selectedId = pemohonMap.get(selectedName); 
        System.out.println("Pemohon terpilih: " + selectedName + " (ID: " + selectedId + ")");

        // Ambil nilai dari combo box
        String paspor = jComboBoxPaspor.getSelectedItem().toString();
        String suratPernyataanJaminan = jComboBoxSPJ.getSelectedItem().toString();
        String rekeningKoranSponsor = jComboBoxRKS.getSelectedItem().toString();
        String cv = jComboBoxCV.getSelectedItem().toString();
        String jadwalKeberangkatan = jComboBoxJadwalKeberangkatan.getSelectedItem().toString();

        System.out.println("Kriteria yang dipilih:");
        System.out.println("  Paspor: " + paspor);
        System.out.println("  Surat Pernyataan Jaminan: " + suratPernyataanJaminan);
        System.out.println("  Rekening Koran Sponsor: " + rekeningKoranSponsor);
        System.out.println("  CV: " + cv);
        System.out.println("  Jadwal Keberangkatan: " + jadwalKeberangkatan);

        // Algoritma Naive Bayes
        System.out.println("Memulai proses prediksi...");
        NaiveBayesAlgoritma nb = new NaiveBayesAlgoritma(trainingData);

        Map<String, String> sample = Map.of(
            "Paspor", paspor,
            "Surat Pernyataan Jaminan", suratPernyataanJaminan,
            "Rekening Koran Sponsor", rekeningKoranSponsor,
            "CV", cv,
            "Jadwal Keberangkatan", jadwalKeberangkatan
        );  

        PredictionResultModel result = nb.predictWithExplanation(sample);
        String hasil = result.getExplanation();
        String label = result.getLabel();
        System.out.println("Hasil prediksi: " + label);
        System.out.println("Penjelasan:\n" + hasil);

        // Tampilkan hasil di JTextArea
        JTextArea txtHasil = new JTextArea();
        txtHasil.setEditable(false);
        txtHasil.setFont(new Font("Monospaced", Font.PLAIN, 12));
        txtHasil.setLineWrap(true);
        txtHasil.setWrapStyleWord(true);
        txtHasil.setText(hasil);

        this.hasil = label;

        JScrollPane scroll = new JScrollPane(txtHasil);
        scroll.setPreferredSize(new Dimension(jPanel2.getWidth(), jPanel2.getHeight()));

        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(scroll, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
        
//        // Simpan hasil ke database
//        DataTrainingModel model = new DataTrainingModel();
//        model.setPemohonId(selectedId); // pakai pemohon_id sekarang
//        model.setKriteria1(paspor);
//        model.setKriteria2(suratPernyataanJaminan);
//        model.setKriteria3(rekeningKoranSponsor);
//        model.setKriteria4(cv);
//        model.setKriteria5(jadwalKeberangkatan);
//        model.setLabel(label);

//        int insertedId = dataTrainingDao.create(model);
//        System.out.println("Data training baru disimpan dengan ID: " + insertedId);
        System.out.println("=== Proses Selesai ===");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxSPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSPJActionPerformed

    private void jComboBoxRKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRKSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            String templateName = "LaporanPrediksiVisa.jrxml";
            InputStream reportStream = MenuView.class.getResourceAsStream("/resources/reports/" + templateName);
            JasperDesign jd = JRXmlLoader.load(reportStream);
            
            Connection dbConnection = DatabaseUtil.getInstance().getConnection();
            JasperReport jr = JasperCompileManager.compileReport(jd);
            
            String selectedPemohon = (String) jComboBoxPemohon.getSelectedItem();
           
            
            HashMap parameter = new HashMap();
            parameter.put("PATH","resources/images/");
            parameter.put("NAMA","VISA :" + selectedPemohon);
            parameter.put("HASIL", hasil);

            JasperPrint jp = JasperFillManager.fillReport(jr,parameter, dbConnection);
            
            // Atur zoom 75% saat viewer dibuka
            JasperViewer viewer = new JasperViewer(jp, false);
            viewer.setZoomRatio(0.75f);
            viewer.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxPasporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPasporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPasporActionPerformed

    private void jComboBoxPemohonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPemohonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPemohonActionPerformed

    private void jComboBoxJadwalKeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJadwalKeberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJadwalKeberangkatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxCV;
    private javax.swing.JComboBox<String> jComboBoxJadwalKeberangkatan;
    private javax.swing.JComboBox<String> jComboBoxPaspor;
    private javax.swing.JComboBox<String> jComboBoxPemohon;
    private javax.swing.JComboBox<String> jComboBoxRKS;
    private javax.swing.JComboBox<String> jComboBoxSPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
